### ISSUE TITLE
给这一题提点意见：Find Minimum in Rotated Sorted Array 

### ISSUE THREAD

**Issue by mmmmmagina** [tg123/leetcode#1]
java并没有做尾递归优化，所以你的代码性能上会比迭代实现要慢点，当然代码优雅一点 ：）

**Comment by tg123** [comment]
感谢 是有这个问题

原始的翻转数组版本 这里没有用 递归
这里做时候就是 自己想应该换一种 写法
https://github.com/tg123/leetcode/blob/gh-pages/search-in-rotated-sorted-array/Solution.java

感觉我那时候写的可读性 不是很好 所以换成这个样子

**Comment by mmmmmagina** [comment]
代码是写给人看的，我其实也更喜欢你的写法。:)
